In [8]:
import numpy as np

# create an np array range 1
un_array = np.array([7,77,777,1234])
print(type(un_array))

<class 'numpy.ndarray'>


In [9]:
# print shape from array
print(type(un_array.shape))

print(un_array.shape)
print(un_array)

<class 'tuple'>
(4,)
[   7   77  777 1234]


In [12]:
print(un_array[0])
print(un_array[1])
print(un_array[2])

un_array[2] = 4

print(un_array[2])

7
77
777
4


In [16]:
other = np.array([[11,12,13],[22,23,24],[35,36,37]])
print("this is another form",other.shape)

this is another form (3, 3)


In [17]:
print("I get a value from numpy like this: ", other[2,0])
print("print complete array")
print(other)

I get a value from numpy like this:  35
print complete array
[[11 12 13]
 [22 23 24]
 [35 36 37]]


## Distintas maneras de crear nd arrays

In [26]:
example_1 = np.zeros((1080,1920))
print(example_1)

example_color = np.zeros((1080,1920,3))
print(example_color)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 ...

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [25]:
example_2 = np.full((2,2), 9.1)
print(example_2)

[[9.1 9.1]
 [9.1 9.1]]


In [22]:
example_3 = np.eye(7,7)
print(example_3)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [23]:
example_4 = np.ones((10,7,2))
print(example_4)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [27]:
example_5 = np.random.random((5,5))
print(example_5)

[[0.54465721 0.88467154 0.98602746 0.4217435  0.43572181]
 [0.26429691 0.03853942 0.5534249  0.51634268 0.33495754]
 [0.06579252 0.49980348 0.15248848 0.26559388 0.35611892]
 [0.36396028 0.76706297 0.59832172 0.20808906 0.23534695]
 [0.51488041 0.99129112 0.7112817  0.70494268 0.31311341]]
